# Generated by Django 4.2.23 on 2025-09-11 19:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Parcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiver_name', models.CharField(max_length=150)),
                ('receiver_phone', models.CharField(max_length=20)),
                ('delivery_type', models.CharField(choices=[('local', 'درون شهری'), ('intercity', 'بین شهری')], max_length=10)),
                ('package_type', models.CharField(choices=[('box', 'بسته'), ('minibox', 'بسته کوچک'), ('nobox', 'بدون جعبه')], default='nobox', max_length=10)),
                ('weight', models.DecimalField(decimal_places=2, help_text='کیلوگرم', max_digits=5)),
                ('value', models.DecimalField(blank=True, decimal_places=0, help_text='ارزش بسته', max_digits=10, null=True)),
                ('need_package', models.BooleanField(default=False)),
                ('length', models.DecimalField(blank=True, decimal_places=1, help_text='cm', max_digits=5, null=True)),
                ('width', models.DecimalField(blank=True, decimal_places=1, help_text='cm', max_digits=5, null=True)),
                ('height', models.DecimalField(blank=True, decimal_places=1, help_text='cm', max_digits=5, null=True)),
                ('estimated_days', models.DecimalField(blank=True, decimal_places=0, help_text='Estimated delivery days', max_digits=3, null=True)),
                ('estimated_price', models.PositiveIntegerField(blank=True, null=True)),
                ('tracking_code', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('created', 'انجام سفارش'), ('picked_up', 'تحویل پیک'), ('in_transit', 'در دست ارسال'), ('delivered', 'تحویل داده شده'), ('cancelled', 'کنسل شده')], default='created', max_length=30)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('destination_city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='shipment.city')),
            ],
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TrackingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=120)),
                ('location', models.CharField(blank=True, max_length=120)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('parcel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='shipment.parcel')),
            ],
            options={
                'ordering': ['-occurred_at'],
            },
        ),
        migrations.AddField(
            model_name='parcel',
            name='destination_province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='shipment.province'),
        ),
        migrations.AddField(
            model_name='parcel',
            name='origin_city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='shipment.city'),
        ),
        migrations.AddField(
            model_name='parcel',
            name='origin_province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='shipment.province'),
        ),
        migrations.AddField(
            model_name='parcel',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_parcels', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='city',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='shipment.province'),
        ),
        migrations.AlterUniqueTogether(
            name='city',
            unique_together={('province', 'name')},
        ),
    ]
