# Generated by Django 4.2.23 on 2025-09-11 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0002_alter_city_unique_together_alter_city_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcel',
            name='receiver_address',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='parcel',
            name='sender_address',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='destination_city',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='destination_province',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='estimated_days',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='origin_city',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='origin_province',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='Province',
        ),
    ]
