# Generated by Django 4.2.23 on 2025-09-08 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(error_messages={'unique': 'The phone number already exists'}, max_length=13, unique=True),
        ),
    ]
