# Generated by Django 4.2.23 on 2025-09-10 00:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(error_messages={'unique': 'The phone number already exists'}, max_length=13, unique=True, validators=[django.core.validators.RegexValidator(regex='^989[0-3,9]\\d{8}$')]),
        ),
    ]
